export default {
  carsPage: 1,
  cars: [],
  carsCount: 1,
  view: 'garage',
  animation: { id: 0 },
  winnersCount: '',
  winners: [{ winner: { id: '', wins: '', time: 0 } }, { car: { name: '', color: '' } }],
  winner: [],
  winnersPage: 1,
  sortBy: '',
  sortOrder: '',
  limitWinners: 10,
  limitGarage: 7,
};
